### ISSUE TITLE
Guava 25.1 dependency added in 0.41 makes Truth unusable for testing projects using older versions of Guava

### ISSUE THREAD

**Issue by ispringer** [google/truth#466]
After upgrading from Truth 0.40 to 0.41, some of my tests are failing with:

```
java.lang.NoSuchMethodError: com.google.common.base.Strings.lenientFormat(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

	at com.google.common.truth.Subject.named(Subject.java:154)
```
My project is stuck on Guava 20.0 for the time being, because we have a dependency on jClouds, which is incompatible with Guava 21 or later.

It seems unreasonable to make Truth only compatible with the very latest version of Guava, which just came out 2 weeks ago. Can you please either downgrade Guava or shade Guava, so it doesn't cause compatibility issues with the production code under test?

**Comment by cpovirk** [comment]
Guava 21 has been out for a year and a half, and we've been deprecating APIs 2 years before removal, so anything we removed in Guava 21 was deprecated at least 3.5 years ago. Guava had always documented that it can remove APIs after a deprecation period (originally 18 months, later 2 years), so jClouds should have been able to address this by now. (That's not to say that they necessarily did anything wrong; perhaps some dependency of theirs is holding things up.)

At the same time, we know that removing things from Guava at all has been painful for people, and we looked at the cost-benefit ratio of the removals we'd done recently and decided that it would have been better for us to stop removing things. Sorry that we didn't do this earlier. Compatibility should at least not be as much of a problem in the future. We have some other work underway to help with compatibility, too. But that doesn't help with your current problem.

All that said, I will see if I can carve out some time to release an 0.42 that removes the Guava 25.1 dependency. We don't really need it; I had just hoped that it would make things _easier_ overall because it meant that users could directly inline deprecated methods, rather than inline them and then replace Truth's `StringUtil.format` with `String.format` or Guava's `Strings.lenientFormat` manually.

**Comment by JakeWharton** [comment]
Shouldn't we be jarjar-ing Guava in the libraries which aren't updating rather than forcing up-to-date libraries to jump through hoops? Why don't you shade Guava in the jclouds dependencies?

**Comment by dimo414** [comment]
> we have a dependency on jClouds, which is incompatible with Guava 21 or later.

Have you filed a bug with that project? That seems like the right place to start.

> It seems unreasonable to make Truth only compatible with the very latest version of Guava

I disagree; it's unreasonable to expect projects to artificially delay improvements because of unrelated downstream build problems. Truth 0.41 is clearly documented to [depend on Guava 25.1](https://github.com/google/truth/blob/36140ea5c0be5389086fd6f3288a2b569dc7815c/core/pom.xml#L13), and Truth 0.40 [depended on Guava 23.4](https://github.com/google/truth/blob/41b494793d6b7632998e3796235e29b0c2fc25ed/core/pom.xml#L13) - so the fact that you were even able to run 0.40 was a lucky coincidence, and never guaranteed. If you can't update Guava, why update Truth? Truth 0.34 was the last release [compatible with Guava 20](https://github.com/google/truth/blob/5dc338c5c6e35a47a7fc8359336ce73d63c8d87b/core/pom.xml#L12).

**Comment by ispringer** [comment]
> Have you filed a bug with that project? That seems like the right place to start.

Yes, I did (https://issues.apache.org/jira/browse/JCLOUDS-1225), and they recently fixed it in jClouds 2.1, so we were able to upgrade Guava in our project. So this is no longer an issue for me, but I still think it is a legitimate issue. 

> I disagree; it's unreasonable to expect projects to artificially delay improvements because of unrelated downstream build problems. 

Why is that unreasonable? Truth is a library. By depending on another library that many projects use in production code, and not shading that library, you are making it more difficult for users to use Truth, and to upgrade to the latest version of Truth to make use of new features. And by using the bleeding edge latest version of that library, you are making it even more difficult.

> If you can't update Guava, why update Truth?

Because they are completely separate libraries. Also, one is a widely used production library, and the other is a testing library.

**Comment by dimo414** [comment]
> Because they are completely separate libraries.

That's just not true. "Truth is owned and maintained by the Guava team" and "it natively supports ... Guava types" ([Truth homepage](http://google.github.io/truth/)). Truth's APIs explicitly depend on Guava - it's not an implementation detail. Suppose Guava introduced a new collection type in v26, it would be entirely reasonable for Truth to immediately introduce a subject for that type in its next release.

I just don't see why Truth should be constrained the way you're describing. If you can't keep your Guava releases up to date, it shouldn't be surprising that you eventually can't keep updating other libraries too. As I said, it's fortunate you were even able to update past 0.34 - there was never any guarantee *that* would work.

**Comment by ispringer** [comment]
Ok, I didn't realize there were subjects for Guava built in to Truth. It seems odd to me that these are in the core and not an extension (JDK8 is an extension, but Guava is not?). In any case, I don't want to argue. I've expressed my opinion, and if you guys disagree, that's cool.
